<?xml version="1.0"?>
<package format="2">
  <name>piper_task</name>
  <version>0.1.0</version>
  <description>Competition pick and place task controller for the Piper arm.</description>

  <maintainer email="syx-369@users.noreply.github.com">syx-369</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>geometry_msgs</depend>
  <depend>piper_msgs</depend>
  <depend>rospy</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>

  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-opencv</exec_depend>
  <exec_depend>rospkg</exec_depend>
  <exec_depend>waypoint_tools</exec_depend>

  <export/>
</package>
